name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.3, 7.4]
        laravel: [^5.5, ^6.0, ^7.0, ^8.0]
        exclude:
          - php: 7.2
            laravel: ^8.0
        include:
          - php: 8.0
            laravel: ^8.0
    name: Test PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: |
           composer require "laravel/framework=${{ matrix.laravel }}" --no-update
           composer update --prefer-dist --no-interaction --no-progress
      - name: Run tests
        run: vendor/bin/phpunit --verbose --coverage-clover coverage.xml

      - name: Upload code coverage
        if: matrix.php == '7.4' && matrix.laravel == '^8.0'
        uses: codecov/codecov-action@v1
